// ---------------------------------------------------------------------------
// email.ts — Send agent output emails via Resend
// ---------------------------------------------------------------------------
import { Resend } from "resend";
import type { ManagerSummary } from "./types";

function getResendClient(): Resend {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) throw new Error("RESEND_API_KEY is not set");
  return new Resend(apiKey);
}

/**
 * Helper: send via Resend and throw if the API returns an error.
 * The Resend SDK v6 does NOT throw on errors — it returns { data, error }.
 */
async function sendOrThrow(
  resend: Resend,
  payload: Parameters<typeof resend.emails.send>[0]
): Promise<string> {
  const { data, error } = await resend.emails.send(payload);
  if (error) {
    throw new Error(
      `Resend API error: ${error.name} — ${error.message}`
    );
  }
  return data?.id ?? "unknown";
}

/**
 * Send the manager summary as an email digest.
 */
export async function sendDigestEmail(summary: ManagerSummary): Promise<void> {
  const from = process.env.EMAIL_FROM ?? "agents@tilthockey.com";
  const to = process.env.EMAIL_TO ?? "chris@tilthockey.com";

  const agentList = summary.agentResults
    .map((r) => `  - ${r.agentName}: ${r.status}`)
    .join("\n");

  const resend = getResendClient();

  await sendOrThrow(resend, {
    from,
    to,
    subject: `[Tilt Agents] Daily Digest — ${new Date().toLocaleDateString()}`,
    text: [
      "Tilt Agent Orchestrator — Daily Digest",
      "=".repeat(44),
      "",
      "Agents that ran:",
      agentList,
      "",
      "Executive Summary:",
      summary.summary,
    ].join("\n"),
  });
}

/**
 * Send a single agent's output as an email (useful for per-agent alerts).
 */
export async function sendAgentEmail(
  agentName: string,
  output: string,
  subject?: string
): Promise<void> {
  const from = process.env.EMAIL_FROM ?? "agents@tilthockey.com";
  const to = process.env.EMAIL_TO ?? "chris@tilthockey.com";

  const resend = getResendClient();

  await sendOrThrow(resend, {
    from,
    to,
    subject: subject ?? `[Tilt Agents] ${agentName} — Output`,
    text: output,
  });
}

// ---------------------------------------------------------------------------
// Analytics report email — sends HTML + plain text, with urgent detection
// ---------------------------------------------------------------------------

export interface AnalyticsEmailOptions {
  to: string[];
  from: string;
  subject: string;
  reportText: string;
  pdfBuffer?: Buffer;
  pdfFilename?: string;
}

/**
 * Send an analytics report email.
 * - If the report contains "🚨", prepends "[URGENT]" to the subject.
 * - Sends both plain text and an HTML version (wrapped in <pre> for tables).
 */
export async function sendAnalyticsReport(
  opts: AnalyticsEmailOptions
): Promise<void> {
  const resend = getResendClient();
  const isUrgent = opts.reportText.includes("🚨");
  const subject = isUrgent ? `[URGENT] ${opts.subject}` : opts.subject;

  const html = `<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a1a; padding: 20px; max-width: 800px; margin: 0 auto; }
  pre { background: #f5f5f5; padding: 16px; border-radius: 8px; overflow-x: auto; font-size: 13px; line-height: 1.5; }
  h1 { font-size: 20px; border-bottom: 2px solid #e5e5e5; padding-bottom: 8px; }
  .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e5e5; font-size: 12px; color: #888; }
</style>
</head>
<body>
<h1>${escapeHtml(subject)}</h1>
<pre>${escapeHtml(opts.reportText)}</pre>
<div class="footer">Generated by Tilt Agent Orchestrator</div>
</body>
</html>`;

  const emailPayload: Parameters<typeof resend.emails.send>[0] = {
    from: opts.from,
    to: opts.to,
    subject,
    text: opts.reportText,
    html,
  };

  if (opts.pdfBuffer && opts.pdfFilename) {
    emailPayload.attachments = [
      {
        filename: opts.pdfFilename,
        content: opts.pdfBuffer,
      },
    ];
  }

  await sendOrThrow(resend, emailPayload);
}

/**
 * Send an error notification when the analytics pipeline fails.
 */
export async function sendErrorNotification(
  to: string[],
  from: string,
  errorMessage: string
): Promise<void> {
  const resend = getResendClient();

  await sendOrThrow(resend, {
    from,
    to,
    subject: "[URGENT] Tilt Analytics Agent — Pipeline Error",
    text: [
      "The Website Analytics Agent encountered an error:",
      "",
      errorMessage,
      "",
      `Timestamp: ${new Date().toISOString()}`,
      "",
      "Please check the logs and environment variables.",
    ].join("\n"),
  });
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
