CREATE TABLE "org_stick_deals" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_name" text NOT NULL,
	"order_url" text,
	"logo_url" text,
	"accent_color" text,
	"discount_pct" integer DEFAULT 15 NOT NULL,
	"kickback_pct" integer DEFAULT 10 NOT NULL,
	"deadline" date NOT NULL,
	"delivery_date" date,
	"contact_name" text,
	"note" text,
	"copy" text,
	"hashtags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"cta" text,
	"graphic_line" text,
	"image_url" text,
	"image_url_square" text,
	"image_url_story" text,
	"email_subject" text,
	"email_body" text,
	"pitch" jsonb DEFAULT 'null'::jsonb,
	"pitch_pdf_url" text,
	"revision_note" text,
	"status" "post_status" DEFAULT 'needs_review' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
